## The below code for the build and deploy= local->docker->aws (with  ci-cd)
#--------------------------------------------------------------------


name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Get code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 3. Build Docker Image
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
      
      # 4. Push to Docker Hub
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
      
      # 5. Deploy to AWS
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            docker stop my-app-container || true
            docker rm my-app-container || true
            docker run -d --name my-app-container -p 8000:8000 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            echo "Deployment complete!"
            docker ps

























## The below code for the build and deploy= local->docker->aws (not ci-cd)
#--------------------------


# name: Build and Deploy

# on:
#   push:
#     branches: [main]  # Triggers when you push to main branch

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout code from GitHub
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Login to Docker Hub
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # Step 3: Build Docker Image
#       - name: Build Docker Image
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/aivihub-api:latest .

#       # Step 4: Push to Docker Hub
#       - name: Push to Docker Hub
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/aivihub-api:latest
